"""Revised and updated

Revision ID: 3ea3f3a9ed3a
Revises: 54d538b247ef
Create Date: 2025-01-25 14:11:02.337514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea3f3a9ed3a'
down_revision = '54d538b247ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muscle_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('required_equipment', sa.String(length=255), nullable=True),
    sa.Column('muscle_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscle_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_plan_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['user_workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('muscleGroup')
    op.drop_table('userWorkouts')
    op.drop_table('users_favorites')
    op.drop_table('exercise')
    op.drop_table('workoutPlanDetails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workoutPlanDetails',
    sa.Column('plan_detail_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['userWorkouts.plan_id'], ),
    sa.PrimaryKeyConstraint('plan_detail_id')
    )
    op.create_table('exercise',
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('required_equipment', sa.VARCHAR(length=255), nullable=True),
    sa.Column('muscle_group_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['muscle_group_id'], ['muscleGroup.muscle_group_id'], ),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('users_favorites',
    sa.Column('favorite_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exercise_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.exercise_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_table('userWorkouts',
    sa.Column('plan_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('plan_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('muscleGroup',
    sa.Column('muscle_group_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('muscle_group_id')
    )
    op.drop_table('workout_plan_details')
    op.drop_table('user_favorites')
    op.drop_table('user_workouts')
    op.drop_table('exercises')
    op.drop_table('muscle_groups')
    # ### end Alembic commands ###
