"""users test

Revision ID: 54d538b247ef
Revises: 1b1511b13fb1
Create Date: 2025-01-20 14:34:38.233409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d538b247ef'
down_revision = '1b1511b13fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dummy_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_field', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
