"""Added colums to tables to satisfy external API

Revision ID: 730bee8a3592
Revises: 88eff22fc4d5
Create Date: 2025-01-28 14:38:41.108290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730bee8a3592'
down_revision = '88eff22fc4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('muscle', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('equipment', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('exercises_muscle_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('required_equipment')
        batch_op.drop_column('description')
        batch_op.drop_column('video_url')
        batch_op.drop_column('muscle_group_id')

    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('exercise_id')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('required_equipment', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('exercises_muscle_group_id_fkey', 'muscle_groups', ['muscle_group_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('instructions')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('equipment')
        batch_op.drop_column('muscle')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
