"""Added exercises field to UserWorkout

Revision ID: a0bda1cb3d7d
Revises: f1d647548f83
Create Date: 2025-02-10 22:11:07.815112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bda1cb3d7d'
down_revision = 'f1d647548f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_workouts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercises', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_workouts', schema=None) as batch_op:
        batch_op.drop_column('exercises')

    # ### end Alembic commands ###
