"""empty message

Revision ID: adb0df9b2127
Revises: fc4b4aaa91f4
Create Date: 2025-02-01 17:26:59.572101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb0df9b2127'
down_revision = 'fc4b4aaa91f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint('exercises_muscle_group_id_fkey', type_='foreignkey')
        batch_op.drop_column('muscle_group_id')

    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'exercises', ['exercise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('exercise_id')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('exercises_muscle_group_id_fkey', 'muscle_groups', ['muscle_group_id'], ['id'])

    # ### end Alembic commands ###
