"""added muscle_group_id to exercise and fixed relationship

Revision ID: d5840a2f9117
Revises: adb0df9b2127
Create Date: 2025-02-03 16:09:48.947897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5840a2f9117'
down_revision = 'adb0df9b2127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'muscle_groups', ['muscle_group_id'], ['id'])

    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.drop_constraint('muscle_groups_exercise_id_fkey', type_='foreignkey')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('muscle_groups_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('muscle_group_id')

    # ### end Alembic commands ###
