"""fix exercise and muscle group relationships

Revision ID: f7a166765b63
Revises: 730bee8a3592
Create Date: 2025-02-01 13:48:41.137703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a166765b63'
down_revision = '730bee8a3592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'muscle_groups', ['muscle_group_id'], ['id'])

    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.drop_constraint('muscle_groups_exercise_id_fkey', type_='foreignkey')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('muscle_groups_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'])
        batch_op.drop_column('description')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('muscle_group_id')

    # ### end Alembic commands ###
