"""Added muscle_group_id to exercises and defined relationships

Revision ID: fc4b4aaa91f4
Revises: 596b07b35ecc
Create Date: 2025-02-01 16:28:05.771515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4b4aaa91f4'
down_revision = '596b07b35ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muscle_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'muscle_groups', ['muscle_group_id'], ['id'])

    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.drop_constraint('muscle_groups_exercise_id_fkey', type_='foreignkey')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muscle_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('muscle_groups_exercise_id_fkey', 'exercises', ['exercise_id'], ['id'])

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('muscle_group_id')

    # ### end Alembic commands ###
